__author__ = "Arturo Gonzalez"
__copyright__ = "Copyright 2017"
__license__ = "MIT"
__version__ = "0.0.1"
__maintainer__ = "arturogonzalez"
__email__ = "arturo@arturosolutions.com.au"
__status__ = "Development"
__url__ = "https://github.com/arturosolutions/train_simulation"
